### ISSUE TITLE
Update READme

### ISSUE THREAD

**Issue by vengatesh99** [Bala-Logesh/SE23-61-Application-Tracking-System#18]
Update Readme to include our enhancements/changes in the project

**Comment by RatishkumarS** [comment]
Final Readme is committed check  commit [#134b84210ff2c0bff6182dcd003119ec89163405](https://github.com/Bala-Logesh/SE23-61-Application-Tracking-System/commit/134b84210ff2c0bff6182dcd003119ec89163405)
