### ISSUE TITLE
CORS dependency issue

### ISSUE THREAD

**Issue by vengatesh99** [Bala-Logesh/SE23-61-Application-Tracking-System#2]
Access to XMLHttpRequest at 'http://localhost:5000/users/signup' from origin 'http://localhost:3000' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.

**Comment by Bala-Logesh** [comment]
I am able to run the application on Firefox. Try using that instead of Chrome and Safari

**Comment by vengatesh99** [comment]
Looks like only the mac users are facing issue when running the application in chrome. Might have to explore why.
