### ISSUE TITLE
Signup actions not working as expected

### ISSUE THREAD

**Issue by SahanaYelchuri** [Bala-Logesh/SE23-61-Application-Tracking-System#3]
![WhatsApp Image 2023-11-18 at 19 24 06_6d7e4b3e](https://github.com/Bala-Logesh/SE23-61-Application-Tracking-System/assets/84435645/86d25714-d6ce-4f45-980d-9c9f4d64cefe)
![WhatsApp Image 2023-11-18 at 19 24 07_cddbb8c5](https://github.com/Bala-Logesh/SE23-61-Application-Tracking-System/assets/84435645/20ec0ffb-88b6-4dd7-94f9-0fcbfbb7bd7c)

After signup, redirect to login page or else at least clear the form data

**Comment by Bala-Logesh** [comment]
This should be an easy fix, I will clear the fields after successful signup and redirect to login page

**Comment by vengatesh99** [comment]
@Bala-Logesh has fixed this. Closing this
