### ISSUE TITLE
MongoDB schema 

### ISSUE THREAD

**Issue by SahanaYelchuri** [Bala-Logesh/SE23-61-Application-Tracking-System#7]
class Users(db.Document):
    """
    Users class. Holds full name, username, password, as well as applications and resumes
    """

    id = db.IntField(primary_key=True)
    fullName = db.StringField()
    username = db.StringField()
    password = db.StringField()
    authTokens = db.ListField()
    applications = db.ListField()
    resume = db.FileField()
    board=db.ListField()

This schema has nesting of more than 2 layers. Can we reduce the nesting levels?

**Comment by vengatesh99** [comment]
Okay, I will split the schema with atmost two layers of nesting and make the changes

**Comment by vengatesh99** [comment]
Have done changes for db Revamping as per the design we discussed and confirmed!
