### ISSUE TITLE
Issue with DB username/pwd

### ISSUE THREAD

**Issue by vengatesh99** [Bala-Logesh/SE23-61-Application-Tracking-System#8]
YAML file has MongoDB username and password visible, which is not a good practice. Can you use environment variable for this.

**Comment by Bala-Logesh** [comment]
We will add .env files for this issue

**Comment by Bala-Logesh** [comment]
Fixed to use dotenv

https://github.com/Bala-Logesh/SE23-61-Application-Tracking-System/commit/3646ca00f8b7519eefb81d4af471bef3016d3943
